language: cpp
sudo: required
dist: trusty
compiler: gcc
before_install:
install:
  - mkdir -p ~/.godot/templates
  - wget -P ~/.godot/templates/ https://github.com/GodotBuilder/godot-builds/releases/download/2.1_20170121/godot.x11.opt.64
  - wget https://github.com/GodotBuilder/godot-builds/releases/download/2.1_20170121/godot.x11.opt.tools.64
  - wget -P ~/.godot/templates/ https://github.com/GodotBuilder/godot-builds/releases/download/2.1_20170121/godot.x11.opt.debug.64
before_script:
script:    
  - mv ~/.godot/templates/godot.x11.opt.64 ~/.godot/templates/linux_x11_64_release
  - mv ~/.godot/templates/godot.x11.opt.debug.64 ~/.godot/templates/linux_x11_64_debug
  - mkdir -p exports/captain
  - chmod 777 ./godot.x11.opt.tools.64
  - ./godot.x11.opt.tools.64 -export "Linux X11" /exports/captain
  - chmod 777 exports/captain
  - ls
after_success:
