language: cpp
android:
  components:
  - build-tools-19.1
  - android-19
notifications:
  email: false
sudo: required
dist: trusty
compiler: gcc
env:
  global:
  - GAME_NAME=captain_holetooth
  - BUILD_SOURCE_URL="https://github.com/GodotBuilder/godot-builds/releases/download/2.1_20170121/"
install:
#
- mkdir -p ~/.godot/templates
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.x11.opt.64
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.x11.opt.debug.64
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.windows.opt.64.exe
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.windows.opt.debug.64.exe
- wget -P ./../ "$BUILD_SOURCE_URL"godot_server.server.opt.tools.64
before_script:
script:
- mv ~/.godot/templates/godot.x11.opt.64 ~/.godot/templates/linux_x11_64_release
- mv ~/.godot/templates/godot.x11.opt.debug.64 ~/.godot/templates/linux_x11_64_debug
- mv ~/.godot/templates/godot.windows.opt.64.exe ~/.godot/templates/windows_64_release.exe
- mv ~/.godot/templates/godot.windows.opt.debug.64.exe ~/.godot/templates/windows_64_debug.exe
- mkdir ./../exports
- chmod 777 ./../godot_server.server.opt.tools.64
- ./../godot_server.server.opt.tools.64 -export "Linux X11" ./../exports/linux.$GAME_NAME.$target_tag
- ./../godot_server.server.opt.tools.64 -export "Windows Desktop" ./../exports/windows.$GAME_NAME.$target_tag.exe
- cd ./../exports/
- zip linux.$GAME_NAME.$target_tag.zip linux.$GAME_NAME.$target_tag data.pck
- zip windows.$GAME_NAME.$target_tag.zip windows.$GAME_NAME.$target_tag.exe data.pck
- ls .
after_success:
deploy:
  provider: releases
  api_key:
    secure: "qKoyg0NzH/JqxNQsSAflmQ+/NKSZYE+PNrv56t4ESoIemhDWfcq+WQpMEODJKDhi0RQu3u2DLCJWB0BCWz/AHJvzw98KPQqukTOy6CkWPi8+UXsPHM0S94DKDVhAJJr/YxySrsI13xwyGT27LEnkhRdC6j8laFO+/8pHV0/XaBFVgZttRYcuFAgzJyc8sAM+cWviaSItXPb+/AhpjwlCFMltSFPVmCRzGyDTcHchEJnkCZMBgCDs3CdoMBhKMg5bb1e6Sb2gi6yzZxDSPMxTHgDqIJOS6xUajCE4N9Lya7WXJeop7LPo1ij4XviPHbei9vcn3DjyAdqr3U6ph9AQgzheDxy1TBVtcHWZ3EJ75PZ/dnrq9m5VJbucy1vzv81KrG9IOvM4SfzkxXEL+WXL0D6m9W0SN2psGZK0TpYUydcSMZM5mfxjRxEa8JQyQYzrz2QVNxz5yLOuOTF+SUGvwOPoZP8eMQ6uOTWx8H40B5qOtBxv/nBSoHLo+cVI/tJkvk0o0rmTsmz5cU5iKgsOgN0UXm6NZwsKgzorMkam1LV7tSo9PJ/plC70IYol3ChQXkwwr9XgYbPO+Jh1AqpkL3b/oMVYjBVQOK6SN/lhJOt/FGMScH0vUwQdyokTnS1TqmxFQaQysBf+S6geLjG6DuLMG+iTg14QFYsAwLDjiiA="
  file:
    - "./../exports/linux.$GAME_NAME.$target_tag.zip"
    - "./../exports/windows.$GAME_NAME.$target_tag.zip"
  skip_cleanup: true
  on:
    repo: Hirnbix/captain-holetooth
    tags: true
