language: cpp
notifications:
  email: false
sudo: required
dist: trusty
compiler: gcc
env:
  global:
    - GAME_NAME=captain_holetooth
    - BUILD_SOURCE_URL="https://github.com/GodotBuilder/godot-builds/releases/download/2.1_20170121/"  
install:
  - mkdir -p ~/.godot/templates
  - wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.x11.opt.64
  - wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.x11.opt.debug.64
  - wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.windows.opt.64.exe
  - wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.windows.opt.debug.64.exe
  - wget -P ./../ "$BUILD_SOURCE_URL"godot_server.server.opt.tools.64
before_script:
script:    
  - mv ~/.godot/templates/godot.x11.opt.64 ~/.godot/templates/linux_x11_64_release
  - mv ~/.godot/templates/godot.x11.opt.debug.64 ~/.godot/templates/linux_x11_64_debug
  - mv ~/.godot/templates/godot.windows.opt.64 ~/.godot/templates/windows_64_release.exe
  - mv ~/.godot/templates/godot.windows.opt.debug.64 ~/.godot/templates/windows_64_debug.exe
  - mkdir ./../exports
  - chmod 777 ./../godot_server.server.opt.tools.64
  - ./../godot_server.server.opt.tools.64 -export "Linux X11" ./../exports/$GAME_NAME.$target_tag
  - zip ./../exports/linux.$GAME_NAME.$target_tag.zip $GAME_NAME.$target_tag data.pck;
  - zip ./../exports/windows.$GAME_NAME.$target_tag.zip $GAME_NAME.$target_tag.exe data.pck;
  - ls ./../exports
after_success:
deploy:
  provider: releases
  api_key:
    secure: "O7UIyEXATIHl7k+AwU0Pm2MZp50MSXGyPYj5pwiHvqVcPMqKigKm606TuUsTefOMcjpa1ADu2IErzYjo//z2Q6I5k7piiwELPdZfiC9tM/yhEPTWa4ObRAa0LT/RG4aCOuDvC0x280gTiviP19KUpELPDSEBzMrJOFoVPnwmd8jJ/sk6d38LK9zG6GxVwqHjIB0kqdRmrc8XHs0dNwTVf35ZCuui/6B+7UAXT8sfSMtKLBeYEbR2ln82aBfHyHSOaSutSDTq2PLMxDFf9Sonf5Ds7q7M4qA+xvlYQXp2Cj0kpP453IDPHEBJWLvghGxzu5I2ZkT/5z0JSBIYOgA8ktiOzTfblDKFT3cFhpxjMenKVqnJW2X46aKqb/Ku/469m2wrm9z1kziKDOTkQsZHZRZImIs5p6Tv3PHr30unoIJcPiN2pgAbFh494vAWt4zgI3+IC5kYzO3ycqu8ydILq97D6lIkc6wDZExCwWbI3WsO107ZbuqRe/g7AMw6ObvpBZUEIaXThjMpbWrJu8WoRDq65ZqcSeJOS/3PUe/MfcHkgElHTfovMihLQLyyX1v738lR7/e8Ht+1wvd9eynSwcVOKSYCsD8GdWlhSpix2lo5KmiLJfGKPV1yKIE0BJtjK/0mWqQpqHg196FHWlyUjOOKpd9oq2oXTKM9c4RGrd0="
  file_glob: true
  file:
    - ./../exports/windows.$GAME_NAME.$target_tag.zip
    - ./../exports/linux.$GAME_NAME.$target_tag.zip
  skip_cleanup: true
  on:
    repo: Hirnbix/captain-holetooth
    tags: true
